import { describe, it, expect } from "vitest";
import { createTestDb } from "../test-db.js";
import { makeCtx } from "../ctx.js";
import { configBehaviors } from "./config.js";
import { projectBehaviors } from "./project.js";
import { issueBehaviors } from "./issue.js";
import { commentBehaviors } from "./comment.js";
import { notificationBehaviors } from "./notification.js";

async function world() {
  const db = await createTestDb();
  const ctx = makeCtx(db);
  const config = configBehaviors(ctx);
  const project = projectBehaviors(ctx);
  const issues = issueBehaviors(ctx);
  const comments = commentBehaviors(ctx);
  const notifications = notificationBehaviors(ctx);

  const admin = await config.createUser({ actorId: "boot", login: "admin", email: "a@x.io", displayName: "Admin", kind: "admin" });
  const role = await config.createRole({ actorId: admin.id, name: "Dev", permissions: ["issue.create", "comment.create"], issuesVisibility: "all" });
  const todo = await config.createStatus({ actorId: admin.id, name: "Todo", category: "todo", sortOrder: 0 });
  const done = await config.createStatus({ actorId: admin.id, name: "Done", category: "done", sortOrder: 1 });
  const priority = await config.createPriority({ actorId: admin.id, name: "Normal" });
  const type = await config.createIssueType({ actorId: admin.id, name: "Bug" });
  const proj = await project.createProject({ actorId: admin.id, identifier: "proj", name: "P" });
  const alice = await config.createUser({ actorId: admin.id, login: "alice", email: "al@x.io", displayName: "Alice" });
  const bob = await config.createUser({ actorId: admin.id, login: "bob", email: "b@x.io", displayName: "Bob" });
  await project.addProjectMember({ actorId: admin.id, projectId: proj.id, userId: alice.id, roleIds: [role.id] });
  const base = { issueTypeId: type.id, priorityId: priority.id };
  return { db, config, project, issues, comments, notifications, admin, todo, done, priority, type, proj, alice, bob, base };
}

describe("notifications generated by writes + read side", () => {
  it("notifies the assignee on create, excludes the actor, and supports read/markRead", async () => {
    const w = await world();
    await w.issues.createIssue({ actorId: w.alice.id, projectId: w.proj.id, ...w.base, subject: "Bug", assigneeIds: [w.bob.id] });

    expect((await w.notifications.getUnreadNotificationCount({ actorId: w.bob.id, recipientId: w.bob.id })).count).toBe(1);
    expect((await w.notifications.getUnreadNotificationCount({ actorId: w.alice.id, recipientId: w.alice.id })).count).toBe(0); // actor not notified

    const list = await w.notifications.listNotifications({ actorId: w.bob.id, recipientId: w.bob.id, isRead: false, pagination: { limit: 20 } });
    expect(list.items[0]).toMatchObject({ eventType: "issue.created", recipientId: w.bob.id });

    await w.notifications.markNotificationRead({ actorId: w.bob.id, notificationId: list.items[0].id });
    expect((await w.notifications.getUnreadNotificationCount({ actorId: w.bob.id, recipientId: w.bob.id })).count).toBe(0);
    await w.db.destroy();
  });

  it("notifies author + assignees on status change and close, and markAll clears them", async () => {
    const w = await world();
    const issue = await w.issues.createIssue({ actorId: w.alice.id, projectId: w.proj.id, ...w.base, subject: "Bug", assigneeIds: [w.bob.id] });
    await w.issues.transitionIssueStatus({ actorId: w.admin.id, issueId: issue.id, toStatusId: w.done.id });

    // alice (author) gets status_changed + closed; bob (assignee) gets created + status_changed + closed
    expect((await w.notifications.getUnreadNotificationCount({ actorId: w.alice.id, recipientId: w.alice.id })).count).toBe(2);
    expect((await w.notifications.getUnreadNotificationCount({ actorId: w.bob.id, recipientId: w.bob.id })).count).toBe(3);

    const marked = await w.notifications.markAllNotificationsRead({ actorId: w.bob.id, recipientId: w.bob.id });
    expect(marked.markedCount).toBe(3);
    expect((await w.notifications.getUnreadNotificationCount({ actorId: w.bob.id, recipientId: w.bob.id })).count).toBe(0);
    await w.db.destroy();
  });
});
